// angular/src/app/album/album.component.ts
import {Component, HostListener, OnInit, SecurityContext} from '@angular/core';
import {ActivatedRoute, NavigationEnd, Router} from '@angular/router';
import {AngularFireStorage} from '@angular/fire/storage';
import {HttpClient} from '@angular/common/http';
import {DomSanitizer, SafeUrl} from '@angular/platform-browser';
import {combineLatest, Subject} from 'rxjs';
import {JobQueue} from '../job/job-queue';
import {TitleService} from '../service/title.service';
import * as JSZip from 'jszip';
import * as FileSaver from 'file-saver';
import {DecryptedImage} from '../model/decrypted-image';

@Component({
  selector: 'app-album',
  templateUrl: './album.component.html',
  styleUrls: ['./album.component.sass']
})
export class AlbumComponent implements OnInit {

  get uploadable(): boolean {
    // 読み込み中か || ファイルリストを持っていないか || 持っているがファイルリストを復号できる正当な鍵を持っている場合に投稿可能
    return !this.loading && (!this.hasFileList || (this.hasFileList && this.validFileList));
  }

  get editable(): boolean {
    // エディット機能が有効もしくは画像の投稿がないとき
    return this.showEdit || this.fileList.length === 0;
  }

  get currentImage(): DecryptedImage {
    return this.imageList[this.fileList.indexOf(this.currentImageName)];
  }

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private storage: AngularFireStorage,
    private http: HttpClient,
    private sanitizer: DomSanitizer,
    private title: TitleService
  ) {
    this.router.events.subscribe(async value => {
      if (!(value instanceof NavigationEnd)) {
        return;
      }

      if (this.route.firstChild == null) {
        this.currentImageName = null;
        this.hasChild = false;
        return;
      }
      const photoParams = await this.route.firstChild.snapshot.params;
      this.currentImageName = photoParams.photo_id;
      this.hasChild = true;
    });
  }

  readQueue: JobQueue = new JobQueue('read');
  encryptQueue: JobQueue = new JobQueue('encrypt');
  uploadQueue: JobQueue = new JobQueue('upload');

  uploadFiles: File[] = [];
  completedCount = 0;
  loadCompletedCount = 0;
  key: string;
  fileList: string[] = [];

  loading = false;
  hasFileList: boolean;
  validFileList: boolean;

  keyPromise: PromiseLike<CryptoKey>;

  hasChild = false;
  album_id: string;
  imageList: DecryptedImage[] = [];
  showPhotoDetail = false;
  showEdit = false;

  currentImageName: string;

  static stringToBuffer(src): ArrayBufferLike {
    return (new Uint16Array([].map.call(src, function (c) {
      return c.charCodeAt(0);
    }))).buffer;
  }

  static bufferToString(buf) {
    return String.fromCharCode.apply('', new Uint16Array(buf));
  }

  static concat(buffer1: ArrayBuffer, buffer2: ArrayBuffer): ArrayBuffer {
    const tmp = new Uint8Array(buffer1.byteLength + buffer2.byteLength);
    tmp.set(new Uint8Array(buffer1), 0);
    tmp.set(new Uint8Array(buffer2), buffer1.byteLength);
    return tmp.buffer as ArrayBuffer;
  }

  ngOnInit() {
    combineLatest(
      this.route.fragment,
      this.route.params
    ).subscribe(value => {
      this.key = value[0].substring(2);
      this.album_id = value[1].album_id;
      this.title.setTitle(this.album_id);
      this.keyPromise = this.importKey();
      return this.loadFileList();
    });
  }

  @HostListener('window:keydown', ['$event'])
  onKeydown($event) {
    if (this.currentImageName != null) {
      const index = this.fileList.indexOf(this.currentImageName);
      if ($event.key === 'ArrowRight') {
        this.currentImageName = this.fileList[Math.min(this.fileList.length - 1, index + 1)];
      }
      if ($event.key === 'ArrowLeft') {
        this.currentImageName = this.fileList[Math.max(0, index - 1)];
      }
    }
  }

  dndFiles(event: DragEvent) {
    try {
      const fileItems = [];
      for (let i = 0; i < event.dataTransfer.items.length; i++) {
        if (event.dataTransfer.items[i].kind === 'file') {
          fileItems.push(event.dataTransfer.items[i]);
        }
      }
      if (fileItems.length === 0) {
        return; // ファイルをドラッグアンドドロップしていないのならば処理しない
      }

      event.stopPropagation();
      event.preventDefault();
      if (event.type === 'dragover') {
        event.dataTransfer.dropEffect = 'copy';
      } else if (event.type === 'drop') {
        this.append(fileItems.map(item => item.getAsFile()));
      }
    } catch (e) {
      console.error(e);
    }
  }

  async loadFileList() {
    if (this.loading) {
      return;
    }
    if (!this.key || !this.album_id) {
      return;
    } // idと鍵の双方が存在しないと
    try {
      this.loading = true;
      const ref = this.storage.ref(this.album_id + '/filelist');
      this.hasFileList = false;
      const url = await ref.getDownloadURL().toPromise();
      this.hasFileList = true;
      const response = await this.http.get(url, {responseType: 'arraybuffer'}).toPromise();
      const iv = response.slice(0, 12);
      const data = response.slice(12);
      const key = await this.keyPromise;
      this.validFileList = false;
      const decrypted = await window.crypto.subtle.decrypt({
        name: 'AES-GCM',
        iv: iv
      }, key, data);
      this.validFileList = true;
      const json = AlbumComponent.bufferToString(decrypted);
      this.fileList = JSON.parse(json);
      this.imageList = [];
      this.loadCompletedCount = 0;
      this.fileList.forEach(async name => {
        const image = await this.loadImage(name);
        const index = this.fileList.indexOf(name);
        this.imageList[index] = image;
        this.loadCompletedCount += 1;
      });
    } catch (e) {
      console.error(e);
    }
    this.loading = false;
  }

  append(files: FileList | File[]) {
    // 重複チェック
    for (let i = 0; i < files.length; i++) {
      if (this.fileList.indexOf(files[i].name) >= 0) {
        alert('すでに登録済みの名前のファイルが選択されています。処理を中止します。');
        return;
      }
    }

    for (let i = 0; i < files.length; i++) {
      this.uploadFiles.push(files[i]);
      this.readQueue.enqueue(async () => {
        const file = files[i];
        const buffer = await new Promise<ArrayBuffer>(resolve => {
          const reader = new FileReader();
          reader.onloadend = () => resolve(reader.result as ArrayBuffer);
          reader.readAsArrayBuffer(file);
        });
        const uploadingFile = new UploadingFile(file.name, buffer);
        this.enqueueCrypto(uploadingFile);
      });
    }
  }

  enqueueCrypto(file: UploadingFile) {
    this.encryptQueue.enqueue(async () => {
      console.log('do enc');
      const iv = window.crypto.getRandomValues(new Uint8Array(12));

      const key = await this.keyPromise;
      const encrypted = await window.crypto.subtle.encrypt({
        name: 'AES-GCM',
        iv: iv,
      }, key, file.buffer);

      file.encryptedBuffer = AlbumComponent.concat(iv.buffer as ArrayBuffer, encrypted);
      this.enqueueUpload(file);
    });
  }

  enqueueUpload(file: UploadingFile) {
    this.uploadQueue.enqueue(async () => {
      const ref = this.storage.ref(this.album_id + '/' + file.name);
      await ref.put(file.encryptedBuffer);
      this.fileList.push(file.name);
      await this.updateFileList();
      this.completedCount += 1;

      const decryptedImage = file.toDecryptedImage(this.sanitizer);
      const tags = decryptedImage.tags;
      if (tags && tags['Orientation'] && tags['Orientation'] !== 1) {
        const rotated = await this.rotate(decryptedImage.originalImageUrl, tags);
        decryptedImage.url = this.sanitizer.bypassSecurityTrustUrl(rotated);
      } else {
        // canvas.toBlob() (this.rotate())は重い処理なので不要な場合（Orientation=1）は行わない
      }

      const index = this.fileList.indexOf(decryptedImage.name);
      this.imageList[index] = decryptedImage;
      this.loadCompletedCount += 1;
    });
  }

  importKey(): PromiseLike<CryptoKey> {
    return window.crypto.subtle.importKey(
      'jwk',
      {
        kty: 'oct',
        k: this.key,
        alg: 'A256GCM',
        ext: true,
      },
      {
        name: 'AES-GCM',
        length: 256
      },
      false, // whether the key is extractable (i.e. can be used in exportKey)
      ['encrypt', 'decrypt'] // can "encrypt", "decrypt", "wrapKey", or "unwrapKey"
    );
  }

  // ファイルリストの更新
  async updateFileList() {

    this.fileList = this.fileList.filter((x, i, self) => self.indexOf(x) === i); // 重複を排除
    const json = JSON.stringify(this.fileList);
    const iv = window.crypto.getRandomValues(new Uint8Array(12));

    const key = await this.keyPromise;
    const decrypted = await window.crypto.subtle.encrypt({
      name: 'AES-GCM',
      iv: iv,
    }, key, AlbumComponent.stringToBuffer(json) as ArrayBuffer);

    const ref = this.storage.ref(this.album_id + '/filelist');
    ref.put(AlbumComponent.concat(iv.buffer as ArrayBuffer, decrypted));
  }

  async loadImage(name: string) {
    if (name == null) {
      return;
    }
    const ref = this.storage.ref(this.album_id + '/' + name);
    const url = await ref.getDownloadURL().toPromise();
    const buffer = await this.http.get(url, {responseType: 'arraybuffer'}).toPromise();
    const key = await this.keyPromise;
    const iv = buffer.slice(0, 12);
    const data = buffer.slice(12);
    const dec = await window.crypto.subtle.encrypt({
      name: 'AES-GCM',
      iv: iv,
    }, key, data);

    const decryptedImage = new DecryptedImage(name, dec, this.sanitizer);

    const tags = decryptedImage.tags;
    if (tags && tags['Orientation'] && tags['Orientation'] !== 1) {
      const rotated = await this.rotate(decryptedImage.originalImageUrl, tags);
      decryptedImage.url = this.sanitizer.bypassSecurityTrustUrl(rotated);
    } else {
      // canvas.toBlob() (this.rotate())は重い処理なので不要な場合（Orientation=1）は行わない
    }

    return decryptedImage;
  }

  // see: https://stackoverflow.com/questions/20600800/js-client-side-exif-orientation-rotate-and-mirror-jpeg-images/31273162#31273162
  async rotate(url: SafeUrl, tags: any) {
    const canvas = document.createElement('canvas');

    const ctx = canvas.getContext('2d');
    const width = tags['PixelXDimension'];
    const height = tags['PixelYDimension'];
    const orientation = tags['Orientation'];

    const img = await new Promise<any>((resolve, reject) => {
      const image = new Image();
      image.onload = () => resolve(image);
      image.onerror = (err) => reject(err);
      image.src = this.sanitizer.sanitize(SecurityContext.URL, url);
    });

    img.width = width;
    img.height = height;

    if ([5, 6, 7, 8].indexOf(orientation) > -1) {
      canvas.width = img.height;
      canvas.height = img.width;
    } else {
      canvas.width = img.width;
      canvas.height = img.height;
    }

    switch (orientation) {
      case 2:
        ctx.transform(-1, 0, 0, 1, img.width, 0);
        break;
      case 3:
        ctx.transform(-1, 0, 0, -1, img.width, img.height);
        break;
      case 4:
        ctx.transform(1, 0, 0, -1, 0, img.height);
        break;
      case 5:
        ctx.transform(0, 1, 1, 0, 0, 0);
        break;
      case 6:
        ctx.transform(0, 1, -1, 0, img.height, 0);
        break;
      case 7:
        ctx.transform(0, -1, -1, 0, img.height, img.width);
        break;
      case 8:
        ctx.transform(0, -1, 1, 0, 0, img.width);
        break;
    }
    ctx.drawImage(img, 0, 0);
    const type = 'image/jpeg';
    const blob = await new Promise<Blob>(resolve => {
      if (canvas.toBlob) {
        canvas.toBlob(result => resolve(result), type);
      } else {
        const dataURL = canvas.toDataURL(type);
        const bin = atob(dataURL.split(',')[1]);
        const buffer = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++) {
          buffer[i] = bin.charCodeAt(i);
        }
        resolve(new Blob([buffer.buffer as ArrayBuffer], {type: type}));
      }
    });
    return URL.createObjectURL(blob);
  }

  async downloadAsZip() {
    const zip = new JSZip();
    for (const image of this.imageList) {
      zip.file(image.name, image.decryptedData, {binary: true});
    }
    const zipFile = await zip.generateAsync({type: 'blob'});
    FileSaver.saveAs(zipFile, `Photos-${this.album_id}.zip`);
  }

  async delete(image: DecryptedImage) {
    const b = confirm('本当に削除してよろしいですか？');
    if (!b) { return; }
    const ref = this.storage.ref(this.album_id + '/' + image.name);
    await ref.delete();

    this.fileList.splice(this.fileList.indexOf(image.name), 1);
    await this.updateFileList();

    this.imageList.splice(this.imageList.indexOf(image), 1);
  }

  gotoPhoto(image: DecryptedImage) {
    this.router.navigate([this.album_id, image.name], {fragment: 'k=' + this.key});
  }
}

class UploadingFile {
  encryptedBuffer: ArrayBuffer;

  constructor(public readonly name: string, public readonly buffer: ArrayBuffer) {

  }

  toDecryptedImage(sanitizer: DomSanitizer): DecryptedImage {
    return new DecryptedImage(this.name, this.buffer, sanitizer);
  }
}


{{currentImageName}}
<app-photo [image]="currentImage" [album_id]="album_id"></app-photo>

<label>
  <input type="checkbox" [(ngModel)]="showEdit" />
  編集
</label>
<label>
  <input type="checkbox" [(ngModel)]="showPhotoDateTime"/>
  撮影日時
</label>
<label>
  <input type="checkbox" [(ngModel)]="showPhotoDetail"/>
  写真詳細
</label>
<li>読み込み処理中: {{loading}}</li>
<li>全画像数: {{fileList.length}}</li>
<li>読み込み完了画像数: {{imageList.length}}</li>

<div *ngIf="editable || fileList.length == 0">
  <p *ngIf="uploadable" (dragover)="dndFiles($event)" (drop)="dndFiles($event)">
    画像を選択
    <input type="file" multiple (change)="append($event.target.files)" />
  </p>
  <p *ngIf="!uploadable">
    アップロードできません。
  </p>

  <ul>
    <li>名前空間使用中: {{hasFileList}}</li>
    <li>暗号鍵の検証に成功: {{validFileList}}</li>
    <li>待機数: {{readQueue.length}}</li>
    <li>読み込み数: {{encryptQueue.length}}</li>
    <li>暗号化完了数: {{uploadQueue.length}}</li>
    <li>アップロード完了数: {{completedCount}}</li>
  </ul>

  <ol>
    <li>画像のファイル名は公開情報になるので、秘匿すべき情報はファイル名に含まないこと。</li>
  </ol>
</div>

<div *ngIf="(fileList.length > 0) && (fileList.length === imageList.length)">
  <button (click)="downloadAsZip()">すべて保存</button>
</div>

<div class="photo-list">
  <div *ngFor="let image of imageList">
    <img [src]="image?.url" *ngIf="image?.url" (click)="gotoPhoto(image)" />
    <div>
      <a [href]="image?.originalImageUrl" download="{{image?.name}}">{{image?.name}}</a>
      <button (click)="delete(image)" *ngIf="editable">削除</button>
    </div>
    <div *ngIf="(image?.tags['DateTimeOriginal'] || image?.tags['DateTime']) && showPhotoDateTime">
      撮影日時: {{image?.tags['DateTimeOriginal'] || image?.tags['DateTime']}}
    </div>
    <div *ngIf="image?.tags && showPhotoDetail">
      Model: {{image?.tags['Model']}},
      SS: {{image?.exposureTime}},
      F: {{image?.tags['FNumber']}},
      ISO: {{image?.tags['ISOSpeedRatings']}},
      焦点距離: {{image?.tags['FocalLength']}}mm,
      <span *ngIf="image?.tags['FocalLengthIn35mmFilm']">
      焦点距離（35mm換算）: {{image?.tags['FocalLengthIn35mmFilm']}}mm
      </span>
      <label>
        <input type="checkbox" [(ngModel)]="image.showFullExif" />
        EXIF
      </label>
      <div *ngIf="image?.showFullExif">
        {{image?.tags | json}}
      </div>
    </div>
  </div>
</div>

// src/app/[...slug]/album.tsx
"use client"

import { useEffect, useRef, useState } from "react";
import { deletePhoto, importKey, loadFileList, loadImage, putFileList, putImage, storage } from "../../lib/firebase";
import { DecryptedImage } from "@/lib/decrypted-image";
import styles from './page.module.css'
import { JobQueue } from "@/lib/job-queue";
import { concat } from "@/lib/common";
import { filetypeinfo } from "magic-bytes.js";
import JSZip from "jszip";
import FileSaver from "file-saver"

export default function Album({ params }: { params: { slug: string[] } }) {
  const album_id = params.slug[0];
  const photo_id = params.slug[1];

  const readQueue = useRef(new JobQueue('read'));
  const cryptoQueue = useRef(new JobQueue('crypto'));
  const uploadQueue = useRef(new JobQueue('upload'));

  const [loading, setLoading] = useState(false);
  const [fileList, setFileList] = useState<string[]>([]);
  const [imageList, setImageList] = useState<DecryptedImage[]>([]);
  const [currentImage, setCurrentImage] = useState<DecryptedImage | null>();
  const [showEdit, setShowEdit] = useState(false);
  const [showPhotoDateTime, setShowPhotoDateTime] = useState(false);
  const [showPhotoDetail, setShowPhotoDetail] = useState(false);

  // カーソルキーによるナビゲーション
  useEffect(() => {
    function handler(event: KeyboardEvent) {
      if (!currentImage) return;
      const index = fileList.indexOf(currentImage.name);
      if (event.key === 'ArrowRight') {
        const nextImage = imageList[Math.min(fileList.length - 1, index + 1)];
        gotoPhoto(nextImage);
      }
      if (event.key === 'ArrowLeft') {
        const nextImage = imageList[Math.max(0, index - 1)];
        gotoPhoto(nextImage);
      }
    }
    function dragover(event: DragEvent) {
      event.preventDefault();
      // ドロップ可能にする
      if (event.dataTransfer) event.dataTransfer.dropEffect = 'copy';
    }
    function drop(event: DragEvent) {
      event.preventDefault();

      const files = event.dataTransfer?.files;
      if (!files || !files.length) return; // ファイルがない場合は何もしない

      // ファイルがある場合は、ファイルを追加する
      append(Array.from(files));
    }
    window.addEventListener('keydown', handler);
    window.addEventListener('dragover', dragover);
    window.addEventListener('drop', drop);
    return () => {
      window.removeEventListener('keydown', handler);
      window.removeEventListener('dragover', dragover);
      window.removeEventListener('drop', drop);
    }
  }, [currentImage, fileList, imageList]);

  // アルバムの読込
  useEffect(() => {
    const hash = window.location.hash.substring(3);
    async function load() {
      try {
        setLoading(true);
        const key = await importKey(hash);
        const fileList = await loadFileList(album_id, key);
        setFileList(fileList);
        // ファイルリストから順次画像を読み込む
        // NOTE: Promise.allすると全てを読み込むまで反映しないので良くない
        fileList.forEach(async name => {
          const image = await loadImage(album_id, name, key);
          setImageList(prev => {
            const images = [...prev, image];
            // fileListによって定義された順番になるようにソートする
            return fileList.map(name => images.filter(i => i.name === name)[0]).filter(i => i);
          });
        });
      } catch (e) {

      }
      setLoading(false);
    }
    load();
  }, [album_id]);

  // 単一フォトの読込
  useEffect(() => {
    setCurrentImage(imageList.filter(i => i.name === photo_id)[0]);
  }, [imageList, photo_id]);

  // shallowナビゲーションを実装
  // NOTE: 一枚画像の表示・非表示・カーソル移動でURLを変更するが、
  //       コンポーネントの再読み込みは行わない。
  function gotoPhoto(image: DecryptedImage | null) {
    if (!image) {
      window.history.pushState({}, "", `/${album_id}${window.location.hash}`);
      setCurrentImage(null);
        return;
    }
    window.history.pushState({}, "", `/${album_id}/${image.name}${window.location.hash}`);
    setCurrentImage(image);
  }

  // ファイル選択された場合の処理
  function onChangeFile(event: React.ChangeEvent<HTMLInputElement>) {
    const files = event.target.files;
    if (!files) return;

    append(Array.from(files));
  }

  // CloudStorageへのファイル追加処理
  function append(files: File[]) {

    for (const file of files) {
      if (fileList.includes(file.name)) {
        alert(`${file.name}はすでに追加されています`);
        return
      }
    }

    Array.from(files).forEach(file => {
      read(file);
    });
  }

  // ファイル読込
  function read(file: File) {
    readQueue.current.enqueue(async () => {
      const buffer = await new Promise<ArrayBuffer>(resolve => {
        const reader = new FileReader();
        reader.onloadend = () => resolve(reader.result as ArrayBuffer);
        reader.readAsArrayBuffer(file);
      });
      crypto({name: file.name, buffer});
    });
  }

  // 暗号化
  function crypto(file: {name: string, buffer: ArrayBuffer}) {
    cryptoQueue.current.enqueue(async () => {
      const hash = window.location.hash.substring(3);
      const key = await importKey(hash);
      const iv = window.crypto.getRandomValues(new Uint8Array(12));
      const encrypted = await window.crypto.subtle.encrypt({
        name: 'AES-GCM',
        iv: iv,
      }, key, file.buffer);

      upload({...file, encryptedBuffer: concat(iv.buffer as ArrayBuffer, encrypted)});
    });
  }

  // アップロード
  function upload(file: {name: string, buffer: ArrayBuffer, encryptedBuffer: ArrayBuffer}) {
    uploadQueue.current.enqueue(async () => {
      const mime = filetypeinfo(Buffer.from(file.buffer))[0].mime;
      if (!mime) throw new Error(`fileType unknown: ${file.name}`);
      await putImage(album_id, file.name, file.encryptedBuffer, mime);
      await appendFileList(file.name);
      setImageList(prev => [...prev, new DecryptedImage(file.name, file.buffer)]);
    });
  }

  // ファイルリストの更新
  async function appendFileList(name: string) {
    const newFileList = [...fileList, name].filter((x, i, self) => self.indexOf(x) === i); // 重複排除
    setFileList(newFileList);
    await updateFileList(newFileList);
  }

  // メタデータの更新
  async function updateFileList(newFileList: string[]) {
    const hash = window.location.hash.substring(3);
    const key = await importKey(hash);
    await putFileList(album_id, newFileList, key);
  }

  // ファイルの削除
  async function deleteImage(image: DecryptedImage) {
    const b = confirm(`${image.name}を削除しますか？`);
    if (!b) return;

    await deletePhoto(album_id, image.name);
    setImageList(prev => prev.filter(i => i.name !== image.name));

    const newFileList = fileList.filter(name => name !== image.name);
    setFileList(newFileList);
    await updateFileList(newFileList);
  }

  // すべての画像をzipしてダウンロード
  async function downloadAsZip() {
    const zip = new JSZip();
    imageList.forEach(image => {
      zip.file(image.name, image.decryptedData, {binary: true});
    });
    const zipFile = await zip.generateAsync({type:"blob"})
    FileSaver.saveAs(zipFile, `Photos-${album_id}.zip`);
  }

  return (
    <div>
      {currentImage && (
        <div className={styles.photo}>
          <img src={currentImage.url} onClick={() => gotoPhoto(null)} />
        </div>
      )}
      <label>
        <input type="checkbox" checked={showEdit} onChange={() => setShowEdit(prev => !prev)} />
        編集
      </label>
      <label>
        <input type="checkbox" checked={showPhotoDateTime} onChange={() => setShowPhotoDateTime(prev => !prev)} />
        撮影日時
      </label>
      <label>
        <input type="checkbox" checked={showPhotoDetail} onChange={() => setShowPhotoDetail(prev => !prev)} />
        写真詳細
      </label>
      <ul>
        <li>読み込み処理中: {loading ? "Loading" : ""}</li>
        <li>全画像数: {fileList.length}</li>
        <li>読み込み完了画像数: {imageList.length}</li>
      </ul>

      {(showEdit || !fileList.length) && (
        <div>
          <p>
            画像を選択
            <input type="file" multiple onChange={onChangeFile} />
          </p>
          <p>
            画像のファイル名は公開情報になるので、秘匿すべき情報はファイル名に含まないこと。
          </p>
        </div>
      )}

      {fileList.length && (
        <div>
          <button onClick={downloadAsZip}>すべての画像をzipでダウンロード</button>
        </div>
      )}

      <div className={styles["photo-list"]}>
        {imageList.map(image => (
          <div key={image.url}>
            <img src={image.url} onClick={() => gotoPhoto(image)} />
            {/* // <img src="image?.url" *ngIf="image?.url" (click)="gotoPhoto(image)" /> */}
            <div>
              <a href={image.originalImageUrl} download={image.name}>{image.name}</a>
              {showEdit && (
                <button onClick={() => deleteImage(image)}>削除</button>
              )}
            </div>
            {showPhotoDateTime && (image.tags['DateTimeOriginal'] || image.tags['DateTime']) && (
              <div>
                撮影日時: {image.tags['DateTimeOriginal'] || image.tags['DateTime']}
              </div>
            )}
            {showPhotoDetail && (
            <div>
              Model: {image.tags['Model']},
              SS: {image.exposureTime},
              F: {image.tags['FNumber']},
              ISO: {image.tags['ISOSpeedRatings']},
              焦点距離: {image.tags['FocalLength']}mm,
              {image.tags['ExposureBiasValue'] && (
                <span>
                焦点距離（35mm換算）: {image.tags['FocalLengthIn35mmFilm']}mm
                </span>
              )}
              <label>
                <input type="checkbox" checked={image.showFullExif} onChange={() => {image.showFullExif = !image.showFullExif; setImageList([...imageList])}} />
                EXIF
              </label>
              {image.showFullExif && (
                <div>
                  {JSON.stringify(image.exifr)}
                </div>
              )}
            </div>
          )}
          </div>
        ))}
      </div>
    </div>
  );
}
